defaults: &defaults
  docker:
    - image: circleci/node:10.0

version: 2
jobs:

  deploy-on-gh-pages: 
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Set configuration
          command: git config --global user.email "$GITHUB_AUTHOR_EMAIL" && git config --global user.name "$GITHUB_AUTHOR_NAME"

      - run: 
          name: Install Dependencies
          command: npm install

      - run: 
          name: Build static
          command: npm run build

      - run: 
          name: Print files 
          command: cd public && ls && cd ..

      - run: 
          name: Checkout to gh-pages 
          command: git checkout gh-pages

      - run: 
          name: Git diff, only filenames
          command: git diff --name-only

      - run: 
          name: Print files
          command: ls
      

workflows:
  version: 2
  main:
    jobs:
      - deploy-on-gh-pages:
          filters:
            branches:
              only: gh-pages-stage