defaults: &defaults
  docker:
    - image: circleci/node:10.15.3

version: 2
jobs:

  deploy-on-gh-pages: 
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Set configuration
          command:  git config --global user.email "$GITHUB_AUTHOR_EMAIL" && 
                    git config --global user.name "$GITHUB_AUTHOR_NAME"

      - run:
          name: Current location
          command: pwd

      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps-

      - run: 
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "package.json" }}

      - run: 
          name: Build static
          command: npm run build

      - run: 
          name: Move build files to tmp
          command:  
                    mkdir /tmp/build && 
                    mkdir /tmp/build/public && 
                    mv public/* /tmp/build/public
                    
      - run: 
          name: Checkout to deploy branch
          command: git checkout $GITHUB_DEPLOY_BRANCH

      - run: 
          name: Move project contant files to tmp
          command:  
                    mv .gitignore /tmp/build &&
                    mv CNAME /tmp/build

      - run: 
          name: Current branch
          command: git branch
          
      - run: 
          name: Git diff, only filenames
          command: git diff --name-only

      - run: 
          name: Remove old files
          command: rm -rf *

      - run: 
          name: List files
          command: ls -all

      - run: 
          name: List files in tmp
          command: cd /tmp/build && ls -all && cd /home/circleci/project

      - run: 
          name: Move back files 
          command: mv /tmp/build/* /home/circleci/project

      - run: 
          name: List files
          command: ls -all

      - run:
          name: Pull changes
          command: git clean -d -f && git pull

      - run:
          name: Add changes
          command: git add .

      - run:
          name: Commit updated package version
          command: git commit -m "Version update [ci skip]"

      - run:
          name: Push upgraded version
          command: git push https://$GITHUB_TOKEN@github.com/silevis/reactgrid-website.git $GITHUB_DEPLOY_BRANCH
      

workflows:
  version: 2
  main:
    jobs:
      - deploy-on-gh-pages:
          filters:
            branches:
              only: gh-pages-stage